#!/bin/bash
mkdir -p ~/.local/state/archy
touch ~/.local/state/archy/first-run.mode

PACMAN_CONF="/etc/pacman.conf"

sed -i '
  # Uncomment [multilib] header
  s|^[[:space:]]*#\s*\[\s*multilib\s*\]|[multilib]|

  # Uncomment Include ONLY between [multilib] and next section
  /^\[multilib\]/,/^\[/{ 
    s|^[[:space:]]*#\s*Include\s*=\s*/etc/pacman.d/mirrorlist|Include = /etc/pacman.d/mirrorlist|
  }

  # Comment Include lines that belong to commented sections
  /^[[:space:]]*#\s*\[/,/^\[/{ 
    s|^[[:space:]]*Include\s*=\s*/etc/pacman.d/mirrorlist|#Include = /etc/pacman.d/mirrorlist|
  }
' "$PACMAN_CONF"

# Setup sudo-less access for first-run
sudo tee /etc/sudoers.d/first-run >/dev/null <<EOF
Cmnd_Alias FIRST_RUN_CLEANUP = /bin/rm -f /etc/sudoers.d/first-run
Cmnd_Alias SYMLINK_RESOLVED = /usr/bin/ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
$USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl
$USER ALL=(ALL) NOPASSWD: /usr/bin/ufw
$USER ALL=(ALL) NOPASSWD: /usr/bin/ufw-docker
$USER ALL=(ALL) NOPASSWD: /usr/bin/gtk-update-icon-cache
$USER ALL=(ALL) NOPASSWD: SYMLINK_RESOLVED
$USER ALL=(ALL) NOPASSWD: FIRST_RUN_CLEANUP
EOF
sudo chmod 440 /etc/sudoers.d/first-run
