#!/bin/bash

sudo pacman -Syu --noconfirm

if ! command -v paru &> /dev/null; then
  echo "Installing paru AUR helper..."
  sudo pacman -S --needed git base-devel --noconfirm
  if [[ ! -d "paru" ]]; then
    echo "Cloning paru repository..."
  else
    echo "paru directory already exists, removing it..."
    rm -rf paru
  fi

  git clone https://aur.archlinux.org/paru.git

  cd paru
  echo "building paru...."
  makepkg -si --noconfirm
  cd ..
  rm -rf paru
else
  echo "paru is already installed"
fi
