#!/bin/bash
sudo mkdir -p /etc/gnupg
sudo cp ~/archsetup/defaults/gpg/dirmngr.conf /etc/gnupg/dirmngr.conf
sudo chmod 644 /etc/gnupg/dirmngr.conf
sudo gpgconf --kill dirmngr || true
sudo gpgconf --launch dirmngr || true
