#!/bin/bash
packages=(
'hyprland',
'uwsm',
'ghostty'
'dolphin',
'wofi',
'xdg-desktop-portal-hyprland',
'qt5-wayland',
'qt6-wayland',
'polkit-kde-agent',
'grim',
'slurp')

for package in "${packages[@]}"; do
    sudo pacman -S --noconfirm --needed $package
done
