#!/bin/bash

AMD="$(lspci | grep -i 'amd.*vga\|amd.*display' || true)"
if [ -n "$AMD" ]; then
  PACKAGES=(
    mesa
    xf86-video-amdgpu
    xf86-video-ati
    libva-mesa-driver
    vulkan-radeon
    lib32-mesa
    lib32-vulkan-radeon
  )

  paru -S --noconfirm --needed "${PACKAGES[@]}"
fi
